# Start EduAI dev stack reachable on your local network (LAN).
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

$lanIp = (
  Get-NetIPAddress -AddressFamily IPv4 |
  Where-Object {
    $_.IPAddress -like '192.168.*' -or
    $_.IPAddress -like '10.*'
  } |
  Select-Object -First 1 -ExpandProperty IPAddress
)

if (-not $lanIp) {
  Write-Error "Could not detect a LAN IPv4 address. Connect to Wi-Fi/Ethernet and retry."
}

$base = "http://$lanIp"
Write-Host ""
Write-Host "EduAI LAN mode - IP: $lanIp" -ForegroundColor Cyan
Write-Host ""

$envLocalPath = Join-Path $Root '.env.local'
$lines = @(
  '# Auto-generated by scripts/dev-lan.ps1 - LAN dev overrides (gitignored)',
  "DEV_LAN_HOST=$lanIp",
  "NEXT_PUBLIC_WEB_URL=${base}:3000",
  "NEXT_PUBLIC_ADMIN_URL=${base}:3002",
  "AUTH_URL=${base}:3000",
  "AUTH_URL_ADMIN=${base}:3002",
  "NEXT_PUBLIC_IDENTITY_SERVICE_URL=${base}:3001",
  "NEXT_PUBLIC_LEARNING_SERVICE_URL=${base}:3003",
  "NEXT_PUBLIC_AI_SERVICE_URL=${base}:3004",
  "NEXT_PUBLIC_ERP_SERVICE_URL=${base}:3005",
  "NEXT_PUBLIC_BILLING_SERVICE_URL=${base}:3006",
  "IDENTITY_SERVICE_URL=${base}:3001",
  "LEARNING_SERVICE_URL=${base}:3003",
  "AI_SERVICE_URL=${base}:3004",
  "ERP_SERVICE_URL=${base}:3005",
  "BILLING_SERVICE_URL=${base}:3006"
)
Set-Content -Path $envLocalPath -Value $lines -Encoding UTF8
Write-Host "Wrote .env.local with LAN URLs" -ForegroundColor Green

foreach ($port in 3000, 3001, 3002, 3003, 3004, 3005, 3006) {
  Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue |
    ForEach-Object {
      Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue
    }
}
Start-Sleep -Seconds 2

Write-Host "Starting backend + frontend (Ctrl+C to stop)..." -ForegroundColor Yellow
Write-Host ""
Write-Host "  Web:   ${base}:3000" -ForegroundColor White
Write-Host "  Admin: ${base}:3002" -ForegroundColor White
Write-Host '  Demo:  *@demo.eduai.in / Demo1234!' -ForegroundColor DarkGray
Write-Host ""

pnpm clean:next
pnpm mvp:dev
